name = "MassConversion"
uuid = "2e54bf2d-ba46-4dd2-9ac8-948a8ef92836"
authors = ["Joshua C. Kynaston <josh.c.kynaston@gmail.com> and contributors"]
version = "0.5.3"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
DocumenterTools = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
